### ISSUE TITLE
mapping function or model issue?

### ISSUE THREAD

**Issue by BaptisteGarcin** [alephmatic/full-stack-ai#7]
```
◐ Installing shadcn-ui components: dialog, form, checkbox                                                               10:54:48 AM
file:///Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/@alephmatic/kirimase/dist/commands/generate/generators/model/schema/index.js:12
        return mappingFunction({ name: field.name }).split("(")[0];
               ^

TypeError: mappingFunction is not a function
    at file:///Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/@alephmatic/kirimase/dist/commands/generate/generators/model/schema/index.js:12:16
    at Array.map (<anonymous>)
    at getUsedTypes (file:///Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/@alephmatic/kirimase/dist/commands/generate/generators/model/schema/index.js:9:10)
    at generateImportStatement (file:///Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/@alephmatic/kirimase/dist/commands/generate/generators/model/schema/index.js:30:27)
    at generateDrizzleSchema (file:///Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/@alephmatic/kirimase/dist/commands/generate/generators/model/schema/index.js:81:29)
    at generateModelContent (file:///Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/@alephmatic/kirimase/dist/commands/generate/generators/model/schema/index.js:145:16)
    at scaffoldModel (file:///Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/@alephmatic/kirimase/dist/commands/generate/generators/model/index.js:19:27)
    at Command.buildSchema (file:///Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/@alephmatic/kirimase/dist/commands/generate/index.js:196:13)
    at Command.listener [as _actionHandler] (/Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/commander/lib/command.js:494:17)
    at /Users/bapt/.npm/_npx/bd905b39f6f3649f/node_modules/commander/lib/command.js:1296:65

Node.js v18.17.0

[10:54:48 AM]  ERROR  Error for kirimase generate: Command failed with exit code 1: npx @alephmatic/kirimase@latest generate --resourceTypes model,trpc_route,views_and_components --table users --fields [{"name":"email","type":"varchar","references":"","notNull":true,"cascade":false},{"name":"name","type":"varchar","references":"","notNull":true,"cascade":false},{"name":"user_type","type":"varchar","references":"","notNull":true,"cascade":false},{"name":"profile_image","type":"text","references":"","notNull":false,"cascade":false},{"name":"age","type":"number","references":"","notNull":false,"cascade":false},{"name":"ethnicity","type":"varchar","references":"","notNull":false,"cascade":false},{"name":"location","type":"varchar","references":"","notNull":false,"cascade":false},{"name":"premium","type":"boolean","references":"","notNull":true,"cascade":false}] --belongsToUser no --index 
```

**Comment by BaptisteGarcin** [comment]
seems to happen only for sqlite
